# Uncomment this line to define a global platform for your project

platform :osx, '10.10'
use_frameworks!

def universal_pods 
pod 'SwiftyTimer'
pod 'SwiftDate'
end


target 'swiftmi' do
universal_pods
end

target 'swiftmiTests' do
universal_pods
end

target 'swiftmiUITests' do
universal_pods
end

