# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

use_frameworks!

target 'swiftmi' do
pod 'SwiftyTimer'
pod 'SwiftDate'
end

target 'swiftmiTests' do

end

target 'swiftmiUITests' do

end

